import "./globals.css";
// import "modern-normalize";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900 transition">
        <Providers>
          <Header />
          <main className="container grow">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
